Repository UMC-CommonPlant/CommonPlant-Server-Refactoring, pull requests merged in 2023-07, with the labels that each got.

#3 [Feat] 예외처리를 위한 ExceptionHandler 로직 추가
  src/main/java/com/umc/commonplant/global/exception/BadRequestException.java
  src/main/java/com/umc/commonplant/global/exception/ErrorResponse.java
  src/main/java/com/umc/commonplant/global/exception/ErrorResponseStatus.java
  src/main/java/com/umc/commonplant/global/exception/ExceptionAdvice.java
  src/main/java/com/umc/commonplant/global/exception/ForbiddenException.java
  src/main/java/com/umc/commonplant/global/exception/GlobalException.java
  src/main/java/com/umc/commonplant/global/exception/MethodNotAllowedException.java
  src/main/java/com/umc/commonplant/global/exception/NotFoundException.java
Labels: chore, 오베

#6 [Feat] 도메인 초기 세팅 완료
  src/main/java/com/umc/commonplant/CommonplantApplication.java
  src/main/java/com/umc/commonplant/domain/BaseTime.java
  src/main/java/com/umc/commonplant/domain/alarm/entity/Alarm.java
  src/main/java/com/umc/commonplant/domain/belong/entity/Belong.java
  src/main/java/com/umc/commonplant/domain/comment/entity/Comment.java
  src/main/java/com/umc/commonplant/domain/friend/entity/Friend.java
  src/main/java/com/umc/commonplant/domain/history/entity/History.java
  src/main/java/com/umc/commonplant/domain/image/entity/Image.java
  src/main/java/com/umc/commonplant/domain/info/entity/Info.java
  src/main/java/com/umc/commonplant/domain/keyword/entity/Keyword.java
  src/main/java/com/umc/commonplant/domain/like/entity/Like.java
  src/main/java/com/umc/commonplant/domain/memo/entity/Memo.java
  src/main/java/com/umc/commonplant/domain/place/entity/Place.java
  src/main/java/com/umc/commonplant/domain/plant/entity/Plant.java
  src/main/java/com/umc/commonplant/domain/qna/entity/QnA.java
  src/main/java/com/umc/commonplant/domain/story/entity/Story.java
  src/main/java/com/umc/commonplant/domain/user/entity/User.java
Labels: feat :arrow_double_up:, 오베 🐻, global

#8 [Chore] .gitignore 수정
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  src/main/java/com/umc/commonplant/global/config/FCMConfig.java
Labels: docs :scroll:, chore :adhesive_bandage:, 벤티 :coffee:
